// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMX6sLgnkw99l217kCfIfH_ZA5tH5QjfU',
    appId: '1:927519068220:web:9135bbe80300b05b0b7339',
    messagingSenderId: '927519068220',
    projectId: 'tudo-745a6',
    authDomain: 'tudo-745a6.firebaseapp.com',
    storageBucket: 'tudo-745a6.appspot.com',
    measurementId: 'G-KGB0G8SWNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8uQ83o-PGPjktYBPdoXXz0XwGTW9J-gM',
    appId: '1:927519068220:android:df623e03e78757d50b7339',
    messagingSenderId: '927519068220',
    projectId: 'tudo-745a6',
    storageBucket: 'tudo-745a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8izE6BW6gVI5pgt4Lhxf4QGvN6Ax65Y',
    appId: '1:927519068220:ios:a4b4ed73a40f3abc0b7339',
    messagingSenderId: '927519068220',
    projectId: 'tudo-745a6',
    storageBucket: 'tudo-745a6.appspot.com',
    iosBundleId: 'com.example.tudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE8izE6BW6gVI5pgt4Lhxf4QGvN6Ax65Y',
    appId: '1:927519068220:ios:a4b4ed73a40f3abc0b7339',
    messagingSenderId: '927519068220',
    projectId: 'tudo-745a6',
    storageBucket: 'tudo-745a6.appspot.com',
    iosBundleId: 'com.example.tudo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMX6sLgnkw99l217kCfIfH_ZA5tH5QjfU',
    appId: '1:927519068220:web:59db9ecc580900730b7339',
    messagingSenderId: '927519068220',
    projectId: 'tudo-745a6',
    authDomain: 'tudo-745a6.firebaseapp.com',
    storageBucket: 'tudo-745a6.appspot.com',
    measurementId: 'G-JBVM0PSZ2E',
  );
}
